//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prestamos.Lite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuota
    {
        public int id { get; set; }
        public Nullable<int> prestamo_id { get; set; }
        public Nullable<int> numero_cuota { get; set; }
        public Nullable<System.DateTime> fecha_pago_cuota { get; set; }
        public Nullable<double> monto_cuota { get; set; }
        public string estado_cuota { get; set; }
        public Nullable<System.DateTime> fecha_pago_cliente { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
    }
}
