//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prestamos.Lite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamo()
        {
            this.Cuotas = new HashSet<Cuota>();
        }
    
        public int numero_operacion { get; set; }
        public Nullable<System.DateTime> fecha_registro_prestamo { get; set; }
        public Nullable<int> tipo_moneda_id { get; set; }
        public Nullable<int> tipo_pago_id { get; set; }
        public Nullable<System.DateTime> fecha_inicio_pago { get; set; }
        public Nullable<System.DateTime> fecha_fin_pago { get; set; }
        public Nullable<double> monto_prestamo { get; set; }
        public Nullable<int> numero_cuotas { get; set; }
        public Nullable<double> intereses { get; set; }
        public Nullable<double> monto_cuotas_sin_interes { get; set; }
        public Nullable<double> monto_cuotas_con_interes { get; set; }
        public Nullable<double> total_prestamo { get; set; }
        public string cliente_id { get; set; }
        public string estado_prestamo { get; set; }
        public string clausulas { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuota> Cuotas { get; set; }
        public virtual Tipo_moneda Tipo_moneda { get; set; }
        public virtual Tipo_pago Tipo_pago { get; set; }
    }
}
