//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prestamos.Lite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id { get; set; }
        public string cliente_id { get; set; }
        public string contraseña { get; set; }
        public Nullable<int> tipo_id { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual tipo_usuario tipo_usuario { get; set; }
    }
}
